// Auto-generated by json2cpp
// C++03-compatible smart pointer for JSON adapters

#ifndef JSON2CPP_JSON_PTR_H
#define JSON2CPP_JSON_PTR_H

namespace json2cpp {

// Detect C++11 or later
#if __cplusplus >= 201103L || (defined(_MSC_VER) && _MSC_VER >= 1900)
    #include <memory>

    template<typename T>
    using UniquePtr = std::unique_ptr<T>;

    #define JSON2CPP_NULLPTR nullptr
    #define JSON2CPP_OVERRIDE override

#else
    // C++03-compatible UniquePtr implementation
    template<typename T>
    class UniquePtr {
    private:
        T* ptr_;

        // Disable copy
        UniquePtr(const UniquePtr&);
        UniquePtr& operator=(const UniquePtr&);

    public:
        explicit UniquePtr(T* p = NULL) : ptr_(p) {}

        ~UniquePtr() {
            delete ptr_;
        }

        T* get() const { return ptr_; }
        T* operator->() const { return ptr_; }
        T& operator*() const { return *ptr_; }

        T* release() {
            T* tmp = ptr_;
            ptr_ = NULL;
            return tmp;
        }

        void reset(T* p = NULL) {
            if (ptr_ != p) {
                delete ptr_;
                ptr_ = p;
            }
        }

        bool operator!() const { return ptr_ == NULL; }
        operator bool() const { return ptr_ != NULL; }
    };

    #define JSON2CPP_NULLPTR NULL
    #define JSON2CPP_OVERRIDE

#endif

} // namespace json2cpp

#endif // JSON2CPP_JSON_PTR_H
