// Auto-generated by json2cpp
// Parser-agnostic JSON adapter interface

#ifndef JSON2CPP_JSON_ADAPTER_H
#define JSON2CPP_JSON_ADAPTER_H

#include <memory>
#include <string>
#include <vector>
#include <cstdint>

namespace json2cpp {

// Read-only JSON value interface
class IJsonReader {
public:
    virtual ~IJsonReader() {}

    // Member existence check
    virtual bool HasMember(const char* key) const = 0;

    // Type checking
    virtual bool IsNull(const char* key) const = 0;
    virtual bool IsBool(const char* key) const = 0;
    virtual bool IsInt(const char* key) const = 0;
    virtual bool IsDouble(const char* key) const = 0;
    virtual bool IsString(const char* key) const = 0;
    virtual bool IsArray(const char* key) const = 0;
    virtual bool IsObject(const char* key) const = 0;

    // Value extraction with default values
    virtual bool GetBool(const char* key, bool defaultVal = false) const = 0;
    virtual int64_t GetInt64(const char* key, int64_t defaultVal = 0) const = 0;
    virtual double GetDouble(const char* key, double defaultVal = 0.0) const = 0;
    virtual std::string GetString(const char* key, const std::string& defaultVal = std::string()) const = 0;

    // Array/Object access (returns std::unique_ptr)
    virtual std::unique_ptr<IJsonReader> GetArray(const char* key) const = 0;
    virtual std::unique_ptr<IJsonReader> GetObject(const char* key) const = 0;

    // Array context methods
    virtual bool IsArrayContext() const = 0;
    virtual size_t GetArraySize() const = 0;
    virtual std::unique_ptr<IJsonReader> GetElement(size_t index) const = 0;

    // Root value type checking (when used as array element or standalone)
    virtual bool IsRootNull() const = 0;
    virtual bool IsRootBool() const = 0;
    virtual bool IsRootInt() const = 0;
    virtual bool IsRootDouble() const = 0;
    virtual bool IsRootString() const = 0;
    virtual bool IsRootArray() const = 0;
    virtual bool IsRootObject() const = 0;

    // Root value extraction
    virtual bool GetRootBool(bool defaultVal = false) const = 0;
    virtual int64_t GetRootInt64(int64_t defaultVal = 0) const = 0;
    virtual double GetRootDouble(double defaultVal = 0.0) const = 0;
    virtual std::string GetRootString(const std::string& defaultVal = std::string()) const = 0;
};

// Write-only JSON builder interface
class IJsonWriter {
public:
    virtual ~IJsonWriter() {}

    // Value setting
    virtual void SetNull(const char* key) = 0;
    virtual void SetBool(const char* key, bool value) = 0;
    virtual void SetInt64(const char* key, int64_t value) = 0;
    virtual void SetDouble(const char* key, double value) = 0;
    virtual void SetString(const char* key, const std::string& value) = 0;

    // Array/Object creation (returns std::unique_ptr)
    virtual std::unique_ptr<IJsonWriter> CreateArray(const char* key) = 0;
    virtual std::unique_ptr<IJsonWriter> CreateObject(const char* key) = 0;

    // Array context methods
    virtual bool IsArrayContext() const = 0;
    virtual void PushNull() = 0;
    virtual void PushBool(bool value) = 0;
    virtual void PushInt64(int64_t value) = 0;
    virtual void PushDouble(double value) = 0;
    virtual void PushString(const std::string& value) = 0;
    virtual std::unique_ptr<IJsonWriter> PushObject() = 0;
};

} // namespace json2cpp

#endif // JSON2CPP_JSON_ADAPTER_H
