// Auto-generated by json2cpp
// JsonCpp adapter implementation

#include "jsoncpp_adapter.h"

namespace json2cpp {

// ============================================================================
// JsonCppReader Implementation
// ============================================================================

JsonCppReader::JsonCppReader(const Json::Value& v)
    : value_(&v), is_array_context_(false) {}

JsonCppReader::JsonCppReader(const Json::Value* v, bool is_array)
    : value_(v), is_array_context_(is_array) {}

bool JsonCppReader::HasMember(const char* key) const {
    return value_ && value_->isObject() && value_->isMember(key);
}

bool JsonCppReader::IsNull(const char* key) const {
    return HasMember(key) && (*value_)[key].isNull();
}

bool JsonCppReader::IsBool(const char* key) const {
    return HasMember(key) && (*value_)[key].isBool();
}

bool JsonCppReader::IsInt(const char* key) const {
    return HasMember(key) && ((*value_)[key].isInt64() || (*value_)[key].isInt());
}

bool JsonCppReader::IsDouble(const char* key) const {
    return HasMember(key) && (*value_)[key].isDouble();
}

bool JsonCppReader::IsString(const char* key) const {
    return HasMember(key) && (*value_)[key].isString();
}

bool JsonCppReader::IsArray(const char* key) const {
    return HasMember(key) && (*value_)[key].isArray();
}

bool JsonCppReader::IsObject(const char* key) const {
    return HasMember(key) && (*value_)[key].isObject();
}

bool JsonCppReader::GetBool(const char* key, bool defaultVal) const {
    return IsBool(key) ? (*value_)[key].asBool() : defaultVal;
}

int64_t JsonCppReader::GetInt64(const char* key, int64_t defaultVal) const {
    if (!HasMember(key)) return defaultVal;
    const Json::Value& v = (*value_)[key];
    if (v.isInt64()) return v.asInt64();
    if (v.isInt()) return static_cast<int64_t>(v.asInt());
    return defaultVal;
}

double JsonCppReader::GetDouble(const char* key, double defaultVal) const {
    return IsDouble(key) ? (*value_)[key].asDouble() : defaultVal;
}

std::string JsonCppReader::GetString(const char* key, const std::string& defaultVal) const {
    return IsString(key) ? (*value_)[key].asString() : defaultVal;
}

UniquePtr<IJsonReader> JsonCppReader::GetArray(const char* key) const {
    if (IsArray(key)) {
        return UniquePtr<IJsonReader>(new JsonCppReader(&(*value_)[key], true));
    }
    return UniquePtr<IJsonReader>(JSON2CPP_NULLPTR);
}

UniquePtr<IJsonReader> JsonCppReader::GetObject(const char* key) const {
    if (IsObject(key)) {
        return UniquePtr<IJsonReader>(new JsonCppReader(&(*value_)[key], false));
    }
    return UniquePtr<IJsonReader>(JSON2CPP_NULLPTR);
}

bool JsonCppReader::IsArrayContext() const {
    return is_array_context_;
}

size_t JsonCppReader::GetArraySize() const {
    if (value_ && value_->isArray()) {
        return value_->size();
    }
    return 0;
}

UniquePtr<IJsonReader> JsonCppReader::GetElement(size_t index) const {
    if (value_ && value_->isArray() && index < value_->size()) {
        return UniquePtr<IJsonReader>(new JsonCppReader(&(*value_)[static_cast<Json::ArrayIndex>(index)], false));
    }
    return UniquePtr<IJsonReader>(JSON2CPP_NULLPTR);
}

bool JsonCppReader::IsRootNull() const {
    return value_ && value_->isNull();
}

bool JsonCppReader::IsRootBool() const {
    return value_ && value_->isBool();
}

bool JsonCppReader::IsRootInt() const {
    return value_ && (value_->isInt64() || value_->isInt());
}

bool JsonCppReader::IsRootDouble() const {
    return value_ && value_->isDouble();
}

bool JsonCppReader::IsRootString() const {
    return value_ && value_->isString();
}

bool JsonCppReader::IsRootArray() const {
    return value_ && value_->isArray();
}

bool JsonCppReader::IsRootObject() const {
    return value_ && value_->isObject();
}

bool JsonCppReader::GetRootBool(bool defaultVal) const {
    return IsRootBool() ? value_->asBool() : defaultVal;
}

int64_t JsonCppReader::GetRootInt64(int64_t defaultVal) const {
    if (!value_) return defaultVal;
    if (value_->isInt64()) return value_->asInt64();
    if (value_->isInt()) return static_cast<int64_t>(value_->asInt());
    return defaultVal;
}

double JsonCppReader::GetRootDouble(double defaultVal) const {
    return IsRootDouble() ? value_->asDouble() : defaultVal;
}

std::string JsonCppReader::GetRootString(const std::string& defaultVal) const {
    return IsRootString() ? value_->asString() : defaultVal;
}

// ============================================================================
// JsonCppWriter Implementation
// ============================================================================

JsonCppWriter::JsonCppWriter(Json::Value& v)
    : value_(&v), is_array_context_(false) {
    if (!value_->isObject()) {
        *value_ = Json::Value(Json::objectValue);
    }
}

JsonCppWriter::JsonCppWriter(Json::Value* v, bool is_array)
    : value_(v), is_array_context_(is_array) {}

void JsonCppWriter::SetNull(const char* key) {
    (*value_)[key] = Json::Value::null;
}

void JsonCppWriter::SetBool(const char* key, bool value) {
    (*value_)[key] = value;
}

void JsonCppWriter::SetInt64(const char* key, int64_t value) {
    (*value_)[key] = Json::Value::Int64(value);
}

void JsonCppWriter::SetDouble(const char* key, double value) {
    (*value_)[key] = value;
}

void JsonCppWriter::SetString(const char* key, const std::string& value) {
    (*value_)[key] = value;
}

UniquePtr<IJsonWriter> JsonCppWriter::CreateArray(const char* key) {
    (*value_)[key] = Json::Value(Json::arrayValue);
    return UniquePtr<IJsonWriter>(new JsonCppWriter(&(*value_)[key], true));
}

UniquePtr<IJsonWriter> JsonCppWriter::CreateObject(const char* key) {
    (*value_)[key] = Json::Value(Json::objectValue);
    return UniquePtr<IJsonWriter>(new JsonCppWriter(&(*value_)[key], false));
}

bool JsonCppWriter::IsArrayContext() const {
    return is_array_context_;
}

void JsonCppWriter::PushNull() {
    value_->append(Json::Value::null);
}

void JsonCppWriter::PushBool(bool value) {
    value_->append(value);
}

void JsonCppWriter::PushInt64(int64_t value) {
    value_->append(Json::Value::Int64(value));
}

void JsonCppWriter::PushDouble(double value) {
    value_->append(value);
}

void JsonCppWriter::PushString(const std::string& value) {
    value_->append(value);
}

UniquePtr<IJsonWriter> JsonCppWriter::PushObject() {
    value_->append(Json::Value(Json::objectValue));
    Json::Value& objRef = (*value_)[value_->size() - 1];
    return UniquePtr<IJsonWriter>(new JsonCppWriter(&objRef, false));
}

} // namespace json2cpp
