// Auto-generated by json2cpp
// nlohmann/json adapter implementation

#ifndef JSON2CPP_NLOHMANN_ADAPTER_H
#define JSON2CPP_NLOHMANN_ADAPTER_H

#include "json_adapter.h"
#include <nlohmann/json.hpp>

namespace json2cpp {

class NlohmannJsonReader : public IJsonReader {
private:
    const nlohmann::json* json_;
    bool is_array_context_;

public:
    explicit NlohmannJsonReader(const nlohmann::json& j);
    explicit NlohmannJsonReader(const nlohmann::json* j, bool is_array);

    // IJsonReader interface
    bool HasMember(const char* key) const JSON2CPP_OVERRIDE;

    bool IsNull(const char* key) const JSON2CPP_OVERRIDE;
    bool IsBool(const char* key) const JSON2CPP_OVERRIDE;
    bool IsInt(const char* key) const JSON2CPP_OVERRIDE;
    bool IsDouble(const char* key) const JSON2CPP_OVERRIDE;
    bool IsString(const char* key) const JSON2CPP_OVERRIDE;
    bool IsArray(const char* key) const JSON2CPP_OVERRIDE;
    bool IsObject(const char* key) const JSON2CPP_OVERRIDE;

    bool GetBool(const char* key, bool defaultVal) const JSON2CPP_OVERRIDE;
    int64_t GetInt64(const char* key, int64_t defaultVal) const JSON2CPP_OVERRIDE;
    double GetDouble(const char* key, double defaultVal) const JSON2CPP_OVERRIDE;
    std::string GetString(const char* key, const std::string& defaultVal) const JSON2CPP_OVERRIDE;

    UniquePtr<IJsonReader> GetArray(const char* key) const JSON2CPP_OVERRIDE;
    UniquePtr<IJsonReader> GetObject(const char* key) const JSON2CPP_OVERRIDE;

    bool IsArrayContext() const JSON2CPP_OVERRIDE;
    size_t GetArraySize() const JSON2CPP_OVERRIDE;
    UniquePtr<IJsonReader> GetElement(size_t index) const JSON2CPP_OVERRIDE;

    bool IsRootNull() const JSON2CPP_OVERRIDE;
    bool IsRootBool() const JSON2CPP_OVERRIDE;
    bool IsRootInt() const JSON2CPP_OVERRIDE;
    bool IsRootDouble() const JSON2CPP_OVERRIDE;
    bool IsRootString() const JSON2CPP_OVERRIDE;
    bool IsRootArray() const JSON2CPP_OVERRIDE;
    bool IsRootObject() const JSON2CPP_OVERRIDE;

    bool GetRootBool(bool defaultVal) const JSON2CPP_OVERRIDE;
    int64_t GetRootInt64(int64_t defaultVal) const JSON2CPP_OVERRIDE;
    double GetRootDouble(double defaultVal) const JSON2CPP_OVERRIDE;
    std::string GetRootString(const std::string& defaultVal) const JSON2CPP_OVERRIDE;
};

class NlohmannJsonWriter : public IJsonWriter {
private:
    nlohmann::json* json_;
    bool is_array_context_;

public:
    explicit NlohmannJsonWriter(nlohmann::json& j);
    explicit NlohmannJsonWriter(nlohmann::json* j, bool is_array);

    // IJsonWriter interface
    void SetNull(const char* key) JSON2CPP_OVERRIDE;
    void SetBool(const char* key, bool value) JSON2CPP_OVERRIDE;
    void SetInt64(const char* key, int64_t value) JSON2CPP_OVERRIDE;
    void SetDouble(const char* key, double value) JSON2CPP_OVERRIDE;
    void SetString(const char* key, const std::string& value) JSON2CPP_OVERRIDE;

    UniquePtr<IJsonWriter> CreateArray(const char* key) JSON2CPP_OVERRIDE;
    UniquePtr<IJsonWriter> CreateObject(const char* key) JSON2CPP_OVERRIDE;

    bool IsArrayContext() const JSON2CPP_OVERRIDE;
    void PushNull() JSON2CPP_OVERRIDE;
    void PushBool(bool value) JSON2CPP_OVERRIDE;
    void PushInt64(int64_t value) JSON2CPP_OVERRIDE;
    void PushDouble(double value) JSON2CPP_OVERRIDE;
    void PushString(const std::string& value) JSON2CPP_OVERRIDE;
    UniquePtr<IJsonWriter> PushObject() JSON2CPP_OVERRIDE;
};

} // namespace json2cpp

#endif // JSON2CPP_NLOHMANN_ADAPTER_H
