// Auto-generated by json2cpp
// nlohmann/json adapter implementation

#include "nlohmann_adapter.h"

namespace json2cpp {

// ============================================================================
// NlohmannJsonReader Implementation
// ============================================================================

NlohmannJsonReader::NlohmannJsonReader(const nlohmann::json& j)
    : json_(&j), is_array_context_(false) {}

NlohmannJsonReader::NlohmannJsonReader(const nlohmann::json* j, bool is_array)
    : json_(j), is_array_context_(is_array) {}

bool NlohmannJsonReader::HasMember(const char* key) const {
    return json_ && json_->is_object() && json_->contains(key);
}

bool NlohmannJsonReader::IsNull(const char* key) const {
    return HasMember(key) && (*json_)[key].is_null();
}

bool NlohmannJsonReader::IsBool(const char* key) const {
    return HasMember(key) && (*json_)[key].is_boolean();
}

bool NlohmannJsonReader::IsInt(const char* key) const {
    return HasMember(key) && (*json_)[key].is_number_integer();
}

bool NlohmannJsonReader::IsDouble(const char* key) const {
    return HasMember(key) && (*json_)[key].is_number();
}

bool NlohmannJsonReader::IsString(const char* key) const {
    return HasMember(key) && (*json_)[key].is_string();
}

bool NlohmannJsonReader::IsArray(const char* key) const {
    return HasMember(key) && (*json_)[key].is_array();
}

bool NlohmannJsonReader::IsObject(const char* key) const {
    return HasMember(key) && (*json_)[key].is_object();
}

bool NlohmannJsonReader::GetBool(const char* key, bool defaultVal) const {
    if (IsBool(key)) {
        return (*json_)[key].get<bool>();
    }
    return defaultVal;
}

int64_t NlohmannJsonReader::GetInt64(const char* key, int64_t defaultVal) const {
    if (IsInt(key)) {
        return (*json_)[key].get<int64_t>();
    }
    return defaultVal;
}

double NlohmannJsonReader::GetDouble(const char* key, double defaultVal) const {
    if (IsDouble(key)) {
        return (*json_)[key].get<double>();
    }
    return defaultVal;
}

std::string NlohmannJsonReader::GetString(const char* key, const std::string& defaultVal) const {
    if (IsString(key)) {
        return (*json_)[key].get<std::string>();
    }
    return defaultVal;
}

UniquePtr<IJsonReader> NlohmannJsonReader::GetArray(const char* key) const {
    if (IsArray(key)) {
        return UniquePtr<IJsonReader>(new NlohmannJsonReader(&(*json_)[key], true));
    }
    return UniquePtr<IJsonReader>(JSON2CPP_NULLPTR);
}

UniquePtr<IJsonReader> NlohmannJsonReader::GetObject(const char* key) const {
    if (IsObject(key)) {
        return UniquePtr<IJsonReader>(new NlohmannJsonReader(&(*json_)[key], false));
    }
    return UniquePtr<IJsonReader>(JSON2CPP_NULLPTR);
}

bool NlohmannJsonReader::IsArrayContext() const {
    return is_array_context_;
}

size_t NlohmannJsonReader::GetArraySize() const {
    if (json_ && json_->is_array()) {
        return json_->size();
    }
    return 0;
}

UniquePtr<IJsonReader> NlohmannJsonReader::GetElement(size_t index) const {
    if (json_ && json_->is_array() && index < json_->size()) {
        return UniquePtr<IJsonReader>(new NlohmannJsonReader(&(*json_)[index], false));
    }
    return UniquePtr<IJsonReader>(JSON2CPP_NULLPTR);
}

bool NlohmannJsonReader::IsRootNull() const {
    return json_ && json_->is_null();
}

bool NlohmannJsonReader::IsRootBool() const {
    return json_ && json_->is_boolean();
}

bool NlohmannJsonReader::IsRootInt() const {
    return json_ && json_->is_number_integer();
}

bool NlohmannJsonReader::IsRootDouble() const {
    return json_ && json_->is_number();
}

bool NlohmannJsonReader::IsRootString() const {
    return json_ && json_->is_string();
}

bool NlohmannJsonReader::IsRootArray() const {
    return json_ && json_->is_array();
}

bool NlohmannJsonReader::IsRootObject() const {
    return json_ && json_->is_object();
}

bool NlohmannJsonReader::GetRootBool(bool defaultVal) const {
    return IsRootBool() ? json_->get<bool>() : defaultVal;
}

int64_t NlohmannJsonReader::GetRootInt64(int64_t defaultVal) const {
    return IsRootInt() ? json_->get<int64_t>() : defaultVal;
}

double NlohmannJsonReader::GetRootDouble(double defaultVal) const {
    return IsRootDouble() ? json_->get<double>() : defaultVal;
}

std::string NlohmannJsonReader::GetRootString(const std::string& defaultVal) const {
    return IsRootString() ? json_->get<std::string>() : defaultVal;
}

// ============================================================================
// NlohmannJsonWriter Implementation
// ============================================================================

NlohmannJsonWriter::NlohmannJsonWriter(nlohmann::json& j)
    : json_(&j), is_array_context_(false) {
    if (!json_->is_object()) {
        *json_ = nlohmann::json::object();
    }
}

NlohmannJsonWriter::NlohmannJsonWriter(nlohmann::json* j, bool is_array)
    : json_(j), is_array_context_(is_array) {}

void NlohmannJsonWriter::SetNull(const char* key) {
    (*json_)[key] = JSON2CPP_NULLPTR;
}

void NlohmannJsonWriter::SetBool(const char* key, bool value) {
    (*json_)[key] = value;
}

void NlohmannJsonWriter::SetInt64(const char* key, int64_t value) {
    (*json_)[key] = value;
}

void NlohmannJsonWriter::SetDouble(const char* key, double value) {
    (*json_)[key] = value;
}

void NlohmannJsonWriter::SetString(const char* key, const std::string& value) {
    (*json_)[key] = value;
}

UniquePtr<IJsonWriter> NlohmannJsonWriter::CreateArray(const char* key) {
    (*json_)[key] = nlohmann::json::array();
    return UniquePtr<IJsonWriter>(new NlohmannJsonWriter(&(*json_)[key], true));
}

UniquePtr<IJsonWriter> NlohmannJsonWriter::CreateObject(const char* key) {
    (*json_)[key] = nlohmann::json::object();
    return UniquePtr<IJsonWriter>(new NlohmannJsonWriter(&(*json_)[key], false));
}

bool NlohmannJsonWriter::IsArrayContext() const {
    return is_array_context_;
}

void NlohmannJsonWriter::PushNull() {
    json_->push_back(JSON2CPP_NULLPTR);
}

void NlohmannJsonWriter::PushBool(bool value) {
    json_->push_back(value);
}

void NlohmannJsonWriter::PushInt64(int64_t value) {
    json_->push_back(value);
}

void NlohmannJsonWriter::PushDouble(double value) {
    json_->push_back(value);
}

void NlohmannJsonWriter::PushString(const std::string& value) {
    json_->push_back(value);
}

UniquePtr<IJsonWriter> NlohmannJsonWriter::PushObject() {
    json_->push_back(nlohmann::json::object());
    return UniquePtr<IJsonWriter>(new NlohmannJsonWriter(&json_->back(), false));
}

} // namespace json2cpp
