// Auto-generated by json2cpp
// RapidJSON adapter implementation

#include "rapidjson_adapter.h"

namespace json2cpp {

// ============================================================================
// RapidJsonReader Implementation
// ============================================================================

RapidJsonReader::RapidJsonReader(const rapidjson::Value& v)
    : value_(&v), is_array_context_(false) {}

RapidJsonReader::RapidJsonReader(const rapidjson::Value* v, bool is_array)
    : value_(v), is_array_context_(is_array) {}

bool RapidJsonReader::HasMember(const char* key) const {
    return value_ && value_->IsObject() && value_->HasMember(key);
}

bool RapidJsonReader::IsNull(const char* key) const {
    return HasMember(key) && (*value_)[key].IsNull();
}

bool RapidJsonReader::IsBool(const char* key) const {
    return HasMember(key) && (*value_)[key].IsBool();
}

bool RapidJsonReader::IsInt(const char* key) const {
    return HasMember(key) && ((*value_)[key].IsInt64() || (*value_)[key].IsInt());
}

bool RapidJsonReader::IsDouble(const char* key) const {
    return HasMember(key) && (*value_)[key].IsDouble();
}

bool RapidJsonReader::IsString(const char* key) const {
    return HasMember(key) && (*value_)[key].IsString();
}

bool RapidJsonReader::IsArray(const char* key) const {
    return HasMember(key) && (*value_)[key].IsArray();
}

bool RapidJsonReader::IsObject(const char* key) const {
    return HasMember(key) && (*value_)[key].IsObject();
}

bool RapidJsonReader::GetBool(const char* key, bool defaultVal) const {
    return IsBool(key) ? (*value_)[key].GetBool() : defaultVal;
}

int64_t RapidJsonReader::GetInt64(const char* key, int64_t defaultVal) const {
    if (!HasMember(key)) return defaultVal;
    const rapidjson::Value& v = (*value_)[key];
    if (v.IsInt64()) return v.GetInt64();
    if (v.IsInt()) return static_cast<int64_t>(v.GetInt());
    return defaultVal;
}

double RapidJsonReader::GetDouble(const char* key, double defaultVal) const {
    return IsDouble(key) ? (*value_)[key].GetDouble() : defaultVal;
}

std::string RapidJsonReader::GetString(const char* key, const std::string& defaultVal) const {
    return IsString(key) ? std::string((*value_)[key].GetString()) : defaultVal;
}

std::unique_ptr<IJsonReader> RapidJsonReader::GetArray(const char* key) const {
    if (IsArray(key)) {
        return std::unique_ptr<IJsonReader>(new RapidJsonReader(&(*value_)[key], true));
    }
    return std::unique_ptr<IJsonReader>(nullptr);
}

std::unique_ptr<IJsonReader> RapidJsonReader::GetObject(const char* key) const {
    if (IsObject(key)) {
        return std::unique_ptr<IJsonReader>(new RapidJsonReader(&(*value_)[key], false));
    }
    return std::unique_ptr<IJsonReader>(nullptr);
}

bool RapidJsonReader::IsArrayContext() const {
    return is_array_context_;
}

size_t RapidJsonReader::GetArraySize() const {
    if (value_ && value_->IsArray()) {
        return value_->Size();
    }
    return 0;
}

std::unique_ptr<IJsonReader> RapidJsonReader::GetElement(size_t index) const {
    if (value_ && value_->IsArray() && index < value_->Size()) {
        return std::unique_ptr<IJsonReader>(new RapidJsonReader(&(*value_)[static_cast<rapidjson::SizeType>(index)], false));
    }
    return std::unique_ptr<IJsonReader>(nullptr);
}

bool RapidJsonReader::IsRootNull() const {
    return value_ && value_->IsNull();
}

bool RapidJsonReader::IsRootBool() const {
    return value_ && value_->IsBool();
}

bool RapidJsonReader::IsRootInt() const {
    return value_ && (value_->IsInt64() || value_->IsInt());
}

bool RapidJsonReader::IsRootDouble() const {
    return value_ && value_->IsDouble();
}

bool RapidJsonReader::IsRootString() const {
    return value_ && value_->IsString();
}

bool RapidJsonReader::IsRootArray() const {
    return value_ && value_->IsArray();
}

bool RapidJsonReader::IsRootObject() const {
    return value_ && value_->IsObject();
}

bool RapidJsonReader::GetRootBool(bool defaultVal) const {
    return IsRootBool() ? value_->GetBool() : defaultVal;
}

int64_t RapidJsonReader::GetRootInt64(int64_t defaultVal) const {
    if (!value_) return defaultVal;
    if (value_->IsInt64()) return value_->GetInt64();
    if (value_->IsInt()) return static_cast<int64_t>(value_->GetInt());
    return defaultVal;
}

double RapidJsonReader::GetRootDouble(double defaultVal) const {
    return IsRootDouble() ? value_->GetDouble() : defaultVal;
}

std::string RapidJsonReader::GetRootString(const std::string& defaultVal) const {
    return IsRootString() ? std::string(value_->GetString()) : defaultVal;
}

// ============================================================================
// RapidJsonWriter Implementation
// ============================================================================

RapidJsonWriter::RapidJsonWriter(rapidjson::Value& v, rapidjson::Document::AllocatorType& a)
    : value_(&v), allocator_(&a), is_array_context_(false) {
    if (!value_->IsObject()) {
        value_->SetObject();
    }
}

RapidJsonWriter::RapidJsonWriter(rapidjson::Value* v, rapidjson::Document::AllocatorType* a, bool is_array)
    : value_(v), allocator_(a), is_array_context_(is_array) {}

void RapidJsonWriter::SetNull(const char* key) {
    rapidjson::Value k(key, *allocator_);
    rapidjson::Value nullVal;
    nullVal.SetNull();
    value_->AddMember(k, nullVal, *allocator_);
}

void RapidJsonWriter::SetBool(const char* key, bool value) {
    rapidjson::Value k(key, *allocator_);
    value_->AddMember(k, rapidjson::Value(value), *allocator_);
}

void RapidJsonWriter::SetInt64(const char* key, int64_t value) {
    rapidjson::Value k(key, *allocator_);
    rapidjson::Value v;
    v.SetInt64(value);
    value_->AddMember(k, v, *allocator_);
}

void RapidJsonWriter::SetDouble(const char* key, double value) {
    rapidjson::Value k(key, *allocator_);
    rapidjson::Value v;
    v.SetDouble(value);
    value_->AddMember(k, v, *allocator_);
}

void RapidJsonWriter::SetString(const char* key, const std::string& value) {
    rapidjson::Value k(key, *allocator_);
    rapidjson::Value v;
    v.SetString(value.c_str(), static_cast<rapidjson::SizeType>(value.length()), *allocator_);
    value_->AddMember(k, v, *allocator_);
}

std::unique_ptr<IJsonWriter> RapidJsonWriter::CreateArray(const char* key) {
    rapidjson::Value k(key, *allocator_);
    rapidjson::Value arr(rapidjson::kArrayType);
    value_->AddMember(k, arr, *allocator_);

    // Get reference to the newly added array
    rapidjson::Value& arrRef = (*value_)[key];
    return std::unique_ptr<IJsonWriter>(new RapidJsonWriter(&arrRef, allocator_, true));
}

std::unique_ptr<IJsonWriter> RapidJsonWriter::CreateObject(const char* key) {
    rapidjson::Value k(key, *allocator_);
    rapidjson::Value obj(rapidjson::kObjectType);
    value_->AddMember(k, obj, *allocator_);

    // Get reference to the newly added object
    rapidjson::Value& objRef = (*value_)[key];
    return std::unique_ptr<IJsonWriter>(new RapidJsonWriter(&objRef, allocator_, false));
}

bool RapidJsonWriter::IsArrayContext() const {
    return is_array_context_;
}

void RapidJsonWriter::PushNull() {
    rapidjson::Value nullVal;
    nullVal.SetNull();
    value_->PushBack(nullVal, *allocator_);
}

void RapidJsonWriter::PushBool(bool value) {
    value_->PushBack(rapidjson::Value(value), *allocator_);
}

void RapidJsonWriter::PushInt64(int64_t value) {
    rapidjson::Value v;
    v.SetInt64(value);
    value_->PushBack(v, *allocator_);
}

void RapidJsonWriter::PushDouble(double value) {
    rapidjson::Value v;
    v.SetDouble(value);
    value_->PushBack(v, *allocator_);
}

void RapidJsonWriter::PushString(const std::string& value) {
    rapidjson::Value v;
    v.SetString(value.c_str(), static_cast<rapidjson::SizeType>(value.length()), *allocator_);
    value_->PushBack(v, *allocator_);
}

std::unique_ptr<IJsonWriter> RapidJsonWriter::PushObject() {
    rapidjson::Value obj(rapidjson::kObjectType);
    value_->PushBack(obj, *allocator_);

    // Get reference to the newly added object
    rapidjson::Value& objRef = (*value_)[value_->Size() - 1];
    return std::unique_ptr<IJsonWriter>(new RapidJsonWriter(&objRef, allocator_, false));
}

} // namespace json2cpp
