// Auto-generated by json2cpp
// RapidJSON adapter implementation

#ifndef JSON2CPP_RAPIDJSON_ADAPTER_H
#define JSON2CPP_RAPIDJSON_ADAPTER_H

#include "json_adapter.h"
#include "rapidjson/document.h"
#include "rapidjson/writer.h"
#include "rapidjson/stringbuffer.h"

namespace json2cpp {

class RapidJsonReader : public IJsonReader {
private:
    const rapidjson::Value* value_;
    bool is_array_context_;

public:
    explicit RapidJsonReader(const rapidjson::Value& v);
    explicit RapidJsonReader(const rapidjson::Value* v, bool is_array);

    // IJsonReader interface
    bool HasMember(const char* key) const override;

    bool IsNull(const char* key) const override;
    bool IsBool(const char* key) const override;
    bool IsInt(const char* key) const override;
    bool IsDouble(const char* key) const override;
    bool IsString(const char* key) const override;
    bool IsArray(const char* key) const override;
    bool IsObject(const char* key) const override;

    bool GetBool(const char* key, bool defaultVal) const override;
    int64_t GetInt64(const char* key, int64_t defaultVal) const override;
    double GetDouble(const char* key, double defaultVal) const override;
    std::string GetString(const char* key, const std::string& defaultVal) const override;

    std::unique_ptr<IJsonReader> GetArray(const char* key) const override;
    std::unique_ptr<IJsonReader> GetObject(const char* key) const override;

    bool IsArrayContext() const override;
    size_t GetArraySize() const override;
    std::unique_ptr<IJsonReader> GetElement(size_t index) const override;

    bool IsRootNull() const override;
    bool IsRootBool() const override;
    bool IsRootInt() const override;
    bool IsRootDouble() const override;
    bool IsRootString() const override;
    bool IsRootArray() const override;
    bool IsRootObject() const override;

    bool GetRootBool(bool defaultVal) const override;
    int64_t GetRootInt64(int64_t defaultVal) const override;
    double GetRootDouble(double defaultVal) const override;
    std::string GetRootString(const std::string& defaultVal) const override;
};

class RapidJsonWriter : public IJsonWriter {
private:
    rapidjson::Value* value_;
    rapidjson::Document::AllocatorType* allocator_;
    bool is_array_context_;

public:
    RapidJsonWriter(rapidjson::Value& v, rapidjson::Document::AllocatorType& a);
    RapidJsonWriter(rapidjson::Value* v, rapidjson::Document::AllocatorType* a, bool is_array);

    // IJsonWriter interface
    void SetNull(const char* key) override;
    void SetBool(const char* key, bool value) override;
    void SetInt64(const char* key, int64_t value) override;
    void SetDouble(const char* key, double value) override;
    void SetString(const char* key, const std::string& value) override;

    std::unique_ptr<IJsonWriter> CreateArray(const char* key) override;
    std::unique_ptr<IJsonWriter> CreateObject(const char* key) override;

    bool IsArrayContext() const override;
    void PushNull() override;
    void PushBool(bool value) override;
    void PushInt64(int64_t value) override;
    void PushDouble(double value) override;
    void PushString(const std::string& value) override;
    std::unique_ptr<IJsonWriter> PushObject() override;
};

} // namespace json2cpp

#endif // JSON2CPP_RAPIDJSON_ADAPTER_H
